package com.portauthority;


public class Strings {

    public static final String action_settings ="Settings";
    public static final String macAddress="MAC";
    public static final String macVendor="Vendor";
    public static final String internalIpLabel="LAN IP";
    public static final String externalIpLabel="WAN IP";
    public static final String fetching="Fetching…";
    public static final String signalLabel="Signal/Speed";
    public static final String hostDiscovery="Discover Hosts";
    public static final String ssid="SSID";
    public static final String bssid="BSSID";
    public static final String scanWellKnownPorts="Scan Well-Known Ports";
    public static final String scanPortRange="Scan Port Range";
    public static final String resetPortRange="Reset Port Range";
    public static final String openPorts="Open Ports";
    public static final String portRangeStart="Start Port";
    public static final String portRangeStop="Stop Port";
    public static final String wifiDisabled="WiFi not enabled";
    public static final String noWifiConnection="No WiFi connection";
    public static final String wanHostHint="URL/IP";
    public static final String scanningWarning="WARNING";
    public static final String domainName="Domain Name";
    public static final String dnsLookup="DNS Lookup";
    public static final String wakeOnLan="Wake Up";
    public static final String waking="Waking up %1$s…";
    public static final String ipAddress="IP Address";
    public static final String startingDnsLookup="Fetching DNS records…";
    public static final String dnsInputError="Enter a domain and select a record type";
    public static final String notConnectedLan="You\'re not connected to the local network";
    public static final String notConnectedWifi="You\'re not connected to a WiFi network!";
    public static final String signalLink="%1$ddBm/%2$dMbps";
    public static final String hostScan="Scanning For Hosts";
    public static final String subnetHosts="%1$d hosts in your subnet";
    public static final String sort="Sort";
    public static final String sortHostname="By hostname";
    public static final String sortVendor="By vendor";
    public static final String copyHostname="Copy hostname";
    public static final String copyIp="Copy IP";
    public static final String copyMac="Copy MAC";
    public static final String getMacVendorFailed="Failed to get MAC vendor";
    public static final String failedOpenDb="Failed to open database";
    public static final String downloadingData="Downloading Data";
    public static final String failedSubnetHosts="Failed to get the number of hosts in subnet";
    public static final String failedSignal="Failed to get signal strength";
    public static final String failedLinkSpeed="Failed to get link speed";
    public static final String failedSsid="Failed to get SSID";
    public static final String failedBssid="Failed to get BSSID";
    public static final String failedWifiManager="Failed to get WifiManager for this device";
    public static final String noWifiInterface="No WiFi interface found";
    public static final String default_notification_channel_id="INVITE";
    public static final String scanningDisclaimer="Please be aware that running port scans against public servers is normally considered malicious.Additionally, running these kinds of scans over your carrier\'s network instead of your own WiFi connection will be slower and will sometimes produce inaccurate results due to traffic shaping.Your carrier can also consider traffic generated by this scan to be malicious."
}